spring:
  sql:
    init:
      mode: embedded
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    defer-datasource-initialization: true